sudo: required
services:
  - docker
language: python
python:
- 3.6
os:
- linux
install:
- pip install --upgrade cwltool==1.0.20181201184214
- pip install --upgrade cwltest
- pip install --upgrade ruamel.yaml==0.15.77
- pip install --upgrade schema-salad==3.0.20181206233650
script: bash run_test.sh --junit-xml=result.xml RUNNER=cwltool
branches:
  only:
  - master
notifications:
  email: false
