name: Deploy to HPC

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag to deploy'
        required: false
        type: string
        default: 'v0.0.31'
      target_host:
        description: 'Target HPC host'
        required: false
        type: choice
        default: 'bmicluster-compute'
        options:
          - bmicluster
          - bmicluster-compute
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - master
      - main

jobs:
  deploy:
    name: Deploy to HPC
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to extract the correct tag
      
      - name: Set Docker tag from git or input
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # Use the input value
            echo "DOCKER_TAG=${{ github.event.inputs.docker_tag }}" >> $GITHUB_ENV
            echo "TARGET_HOST=${{ github.event.inputs.target_host }}" >> $GITHUB_ENV
          else
            # For workflow_run trigger, read the default tag from the docker-build.yml file
            DOCKER_TAG=$(grep -oP 'DOCKER_TAG="v\d+\.\d+\.\d+"' tools/dockerfiles/scidap-deseq-Dockerfile || echo "v0.0.31")
            # If tag not found, use the default
            if [ -z "$DOCKER_TAG" ]; then
              DOCKER_TAG="v0.0.31"
            fi
            echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
            echo "TARGET_HOST=bmicluster-compute" >> $GITHUB_ENV
          fi
          
          echo "Using Docker tag: $DOCKER_TAG"
          echo "Using target host: $TARGET_HOST"
      
      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -x  # Echo commands for better debugging
          
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Debug: Check if secret is available
          echo "Checking if SSH_PRIVATE_KEY secret is available..."
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "ERROR: SSH_PRIVATE_KEY secret is empty or not set"
            exit 1
          fi
          
          # Create the SSH key with proper format
          printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          
          # Debug: Check key file content
          echo "Checking key file content..."
          if [ ! -s ~/.ssh/id_ed25519 ]; then
            echo "ERROR: Key file is empty"
            exit 1
          fi
          
          # Verify the key format
          if ! grep -q "BEGIN OPENSSH PRIVATE KEY" ~/.ssh/id_ed25519; then
            echo "ERROR: Key does not contain proper OpenSSH format"
            echo "First line of key:"
            head -n 1 ~/.ssh/id_ed25519
            echo "Last line of key:"
            tail -n 1 ~/.ssh/id_ed25519
            echo "Key file size:"
            ls -l ~/.ssh/id_ed25519
            exit 1
          fi
          
          # Set proper permissions
          chmod 600 ~/.ssh/id_ed25519
          
          # Check key format validity
          echo "Key fingerprint:"
          ssh-keygen -l -f ~/.ssh/id_ed25519 || {
            echo "ERROR: Invalid key format"
            echo "Key contents (first line):"
            head -n 1 ~/.ssh/id_ed25519
            echo "Key file size:"
            ls -l ~/.ssh/id_ed25519
            exit 1
          }
          
          # Start SSH agent
          eval $(ssh-agent -s)
          ssh-add -v ~/.ssh/id_ed25519 || {
            echo "ERROR: Failed to add key to SSH agent"
            echo "SSH agent status:"
            ssh-agent
            echo "Key file permissions:"
            ls -l ~/.ssh/id_ed25519
            exit 1
          }
          
          # Create SSH config - MODIFIED to work with commands
          cat > ~/.ssh/config << EOF
          Host bmicluster
            HostName bmiclusterp.chmcres.cchmc.org
            User pavb5f
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            ConnectTimeout 30
            ServerAliveInterval 30
            ServerAliveCountMax 3
          
          Host bmicluster-compute
            HostName bmicluster-compute
            User pavb5f
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            ConnectTimeout 60
            ProxyCommand ssh -W %h:%p bmicluster
            ServerAliveInterval 30
            ServerAliveCountMax 3
          EOF
          
          # Set proper permissions for config
          chmod 600 ~/.ssh/config
          
          # Show system information
          echo "=== SYSTEM INFO ==="
          uname -a
          which ssh
          ssh -V
      
      - name: Test SSH connection
        run: |
          # Use the environment variable explicitly with proper debugging
          echo "Testing SSH connection to $TARGET_HOST..."
          
          # Make sure SSH agent is running
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          
          # Test connection with timeout and detailed debugging
          timeout 60s ssh -v $TARGET_HOST "hostname" || {
            echo "ERROR: SSH connection failed"
            echo "Checking key permissions:"
            ls -la ~/.ssh/id_ed25519
            echo "Checking config permissions:"
            ls -la ~/.ssh/config
            echo "Checking SSH config:"
            cat ~/.ssh/config
            echo "Checking loaded keys:"
            ssh-add -l || echo "No keys loaded"
            echo "Testing direct connection to jump host:"
            timeout 30s ssh -v bmicluster "echo Jump host connection succeeded" || echo "Failed to connect to jump host"
            exit 1
          }
      
      - name: Deploy to HPC
        run: |
          # Use environment variables
          echo "Deploying docker tag: $DOCKER_TAG to host: $TARGET_HOST"
          
          # Deploy using the deployment script
          # Ensure script has execute permissions
          chmod +x ./deploy.sh
          
          # Pass environment variables to the script
          ./deploy.sh
          
          # Verify deployment using a simpler command that's compatible with ProxyJump
          echo "Verifying deployment..."
          if ssh $TARGET_HOST "hostname"; then
            echo "Connection successful!"
            # Try to check if container is running
            ssh $TARGET_HOST "docker ps | grep -E '($DOCKER_TAG|scidap-deseq)'" || echo "Container not visible but connection succeeded"
          else
            echo "WARNING: Could not verify deployment - connection failed"
            # Don't fail the pipeline
          fi
      
      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519 ~/.ssh/config 