name: Deploy to HPC with Singularity

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch:  # Allow manual triggering

jobs:
  debug:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Debug environment
        run: |
          echo "Running as: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "Host: $(hostname)"
          echo "PATH: $PATH"
          ls -la
          
      - name: Test SSH config
        run: |
          echo "SSH config:"
          cat ~/.ssh/config || echo "No SSH config found"
          
          echo "Testing SSH connection to bmicluster:"
          ssh -v bmicluster "hostname" || echo "Connection to bmicluster failed"
          
      - name: Check SSH keys
        run: |
          echo "Available SSH keys:"
          ls -la ~/.ssh/
          ssh-add -l || echo "No SSH keys in agent"
          
  deploy:
    needs: debug
    runs-on: self-hosted
    env:
      DOCKER_TAG: v0.0.30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Make script executable
        run: chmod +x scripts/deploy_to_hpc.sh
      
      - name: Verify environment
        run: |
          echo "Running on host: $(hostname) as user: $(whoami)"
          echo "Working directory: $(pwd)"
          echo "Contents of scripts directory:"
          ls -la scripts/
          echo "SSH test command:"
          ssh -v bmicluster "hostname"
          
      - name: Copy deployment script to HPC
        run: |
          scp scripts/deploy_to_hpc.sh bmicluster-compute:/tmp/deploy_to_hpc.sh
          
      - name: Execute deployment on HPC
        run: |
          ssh bmicluster-compute << 'EOF'
            chmod +x /tmp/deploy_to_hpc.sh
            /tmp/deploy_to_hpc.sh ${{ env.DOCKER_TAG }}
            rm /tmp/deploy_to_hpc.sh  # Clean up
          EOF
          
      - name: Verify deployment
        run: |
          ssh bmicluster-compute "ls -la /data/barskilab/scidap_server/singularity_images/biowardrobe2_scidap-deseq:*.sif && cat /data/barskilab/scidap_server/singularity_images/scidap-deseq-version.txt" 