name: Deploy to HPC with Singularity

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
  workflow_dispatch:  # Allow manual triggering

jobs:
  test_connection:
    runs-on: self-hosted
    steps:
      - name: SSH to jump host
        run: |
          echo "Testing connection to jump host:"
          ssh -v bmicluster "hostname && whoami"
      
      - name: SSH to compute node
        run: |
          echo "Testing connection to compute node:"
          ssh -v bmicluster-compute "hostname && whoami"
          
      - name: Test directory access
        run: |
          echo "Testing access to target directory:"
          ssh bmicluster-compute "ls -la /data/barskilab/scidap_server || echo 'Cannot access directory'"
          
      - name: Test Singularity
        run: |
          echo "Testing Singularity module:"
          ssh bmicluster-compute << 'EOF'
          # Try to load the module
          echo "Loading module..."
          module load singularity/3.7.0 || echo "Failed to load module"
          
          # Check if singularity is available
          echo "Checking singularity command:"
          which singularity || echo "Singularity command not found"
          
          # Check singularity version
          echo "Checking singularity version:"
          singularity --version || echo "Failed to get version"
          
          # Create a test temp directory
          echo "Creating test directory:"
          TEMP_DIR=$(mktemp -d)
          cd "${TEMP_DIR}"
          pwd
          
          # Test singularity pull to verify it works
          echo "Testing a very small singularity pull (will take a moment):"
          singularity pull docker://alpine:latest || echo "Failed to pull test image"
          
          # Clean up
          cd - 
          rm -rf "${TEMP_DIR}"
          EOF
          
  mini_deploy:
    needs: test_connection
    runs-on: self-hosted
    env:
      DOCKER_TAG: v0.0.30
    steps:
      - name: Create minimal deploy script
        run: |
          cat > /tmp/mini_deploy.sh << 'EOL'
          #!/bin/bash
          set -e  # Exit on error
          
          # Configuration
          IMAGE_NAME="biowardrobe2/scidap-deseq"
          SINGULARITY_IMAGE_DIR="/data/barskilab/scidap_server/singularity_images"
          VERSION="${1:-v0.0.30}" 
          SINGULARITY_FILENAME="biowardrobe2_scidap-deseq:${VERSION}.sif"
          
          echo "Running as: $(whoami) on $(hostname)"
          echo "Creating directory: ${SINGULARITY_IMAGE_DIR}"
          mkdir -p "${SINGULARITY_IMAGE_DIR}"
          
          echo "Loading singularity module..."
          module load singularity/3.7.0
          
          echo "Singularity version: $(singularity --version)"
          
          # Create a version file only (without pulling the image)
          echo "Creating version file only..."
          echo "${VERSION}" > "${SINGULARITY_IMAGE_DIR}/scidap-deseq-version.txt"
          
          echo "Success! Created: ${SINGULARITY_IMAGE_DIR}/scidap-deseq-version.txt"
          EOF
          
      - name: Copy minimal script to compute node
        run: |
          scp /tmp/mini_deploy.sh bmicluster-compute:/tmp/mini_deploy.sh
          ssh bmicluster-compute "chmod +x /tmp/mini_deploy.sh"
          
      - name: Run minimal deployment
        run: |
          ssh bmicluster-compute "/tmp/mini_deploy.sh ${{ env.DOCKER_TAG }}"
          
      - name: Verify minimal deployment
        run: |
          ssh bmicluster-compute "cat /data/barskilab/scidap_server/singularity_images/scidap-deseq-version.txt || echo 'Version file not found'" 