name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'Dockerfile'
      - 'tools/dockerfiles/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'Dockerfile'
      - 'tools/dockerfiles/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag to build'
        required: false
        default: 'v0.0.31'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip running on pull request if it's from the same repository (avoids duplicate runs)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    
    outputs:
      docker_tag: ${{ steps.set-tag.outputs.docker_tag }}
      
    env:
      DOCKER_IMAGE_NAME: scidap-deseq
      DOCKER_HUB_REPO: biowardrobe2
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set Docker Tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.docker_tag }}" != "" ]; then
            DOCKER_TAG="${{ github.event.inputs.docker_tag }}"
          else
            DOCKER_TAG="v0.0.31"
          fi
          echo "docker_tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT
          echo "Using Docker tag: ${DOCKER_TAG}"
          
          # Convert repository owner to lowercase for Docker tags
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_owner_lowercase=${REPO_OWNER_LOWERCASE}" >> $GITHUB_OUTPUT
          echo "Repository owner (lowercase): ${REPO_OWNER_LOWERCASE}"
          
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: tools/dockerfiles
          file: tools/dockerfiles/scidap-deseq-Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ steps.set-tag.outputs.repo_owner_lowercase }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.set-tag.outputs.docker_tag }}
            ghcr.io/${{ steps.set-tag.outputs.repo_owner_lowercase }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_HUB_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.set-tag.outputs.docker_tag }}
            ${{ env.DOCKER_HUB_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Save Docker tag as artifact
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p ./artifacts
          echo "${{ steps.set-tag.outputs.docker_tag }}" > ./artifacts/docker_tag.txt
          
      - name: Upload Docker tag artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: docker_tag_artifact
          path: ./artifacts/docker_tag.txt
          retention-days: 1